name: Build mkdocs pages and publish to S3 bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check and set
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force

      - name: Build pages and publish to S3
        uses: sys3/mkdocs-s3-publish-action@main
        env:
          S3_LOCATION: ${{ secrets.AWS_S3_LOCATION }}
          S3_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          S3_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          
