name: Build + Deploy docs
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
jobs:
  main:
    name: Build + Deploy
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      # checkout the private repo containing the action to run
      - name: build and copy docs
        uses: gameclosure/mkdocs-publish-s3-action@master
        env:
          S3_PATH: "${AWS_S3_LOCATION}"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CHANGELOG: false # generate a changelog file out of Github release notes
          CHANGELOG_STRIP_PATTERN: https?:\/\/[^ ]+ # optional strip pattern to run on the generated changelog
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required if generating a changelog
          TYPEDOC: true # generate Typescript API documentation with typedoc
      
